language: python
python:
  - "3.4"
  - "3.5"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: NPsAWN17osX6UiNsKm4eeiQ9feU98stNJ1qKKzJaYqq5IHITeYZtrZSOFay7QYv0Xyp/BCsYuofPX6Ht0be27JN5fYCcmiScQOu7NUhjKN7ctFxg+oJVGLiLNnUHnkHKD2WSouSny0cLYlAI3o5Np4RUQ3g8dEQFIrjrbLQCXrJwhr7/iPAk/joDsixHsYReR1e2w387/rVFz/SG0Khm6KCVxYniPygA7wBkASqfoMJorViLITDg4Jon0PsM9SxvAsMiHoNPCDILfIYW0G2M9/pU8SxVbXtSOerDpUaC+DEozrmPQvkSKFbShG6lenTno5lMB6UHSycNC3khxRcP3DZ7DI0L4bH7ZhAudC0n10UBmLrrqhQ2eBEXGT/8vLxjeXdAyaWA61VKERA7OtusSPNXEhJHKk6eUdPQWDN+kqq2lzJIat67kRwzCkkCHqqp0s5L0RU3qk0tyPhuasdLm9zC1gfqlTrRuLSFf+bWv86NQffsrsBst9Hgm5uQ9Ap6uHZLz6bvSXdVxgROncJ4QVBIvEuuEu+WGKiNigDD3ufDxX0qW8QJWcz0tnlLCo1IykNSbIRwU68CxjvriBChA/dWNuTI0eWsGY4aNGBJPzcTW0RWtC/e85X1dQZuD/WoMVRUr9CdZsaYazNG4cPZgwgQr2g51Vco5YUM1qmxBsM=
    - secure: Dlqrzv3q+E9MNx3h0TnwccWZw9zivZhjPmMfKYEK5rIS6sI/nThnxi37U3VOW34Y/HKcMKq7TLDt5x4RJoZb4t9TI79tu6VOQ0E421QNGgoGG9WRYe/93mirUW1N/PqFGucClWfinCEQ1ijey59AYOT525ExYzYgcIJKKdRadQhSGAbuu5yra90Znjwwj8MmXxy8r44NpCc4AUFlj2oTH3mu7/iL1/2CjDyoqMrkx+5+e1/REXNRJZOjDhmjsZtQJPmXnlgngsavA9Gk4YfKzKCbTLr5m3X0561XbR8VfWt19fLXI8kO/TcYrC4Mf0lD+5JvBvh9iKVBcKvFQ7puxC3RF02qtCJ5T5IzNjxnpeIgK4ckGiFpa0LThyPMVGXlMlJ8qXV6wCCyg15Osxmb3F3IaNX15VNEVN3R37blFnsmzaayn/TymhsGPyc0+aGHmFntwdUOlNC6ZV01wJY/9IZNJKr+uUOlf7eIz/NHzsO/8nC/mPn5fpQ1eZ0eB4/Pek2ZIwTSKjtiws7jX0RL1ABEh3tIjAsG1SvUhmJeNt8yqn7r00PbBc1w81itF8HT5HeMHI6YHB3o/Tb/qnRcYiQ2F7vrUSiIKV7zBxJ+ERzZ/9sfmPO0JZwOSXeP1y0MqBf98Bdp477FDlJ3GfO1BTDV95TF6xYjkaRVxIwRL8s=
before_install:
  - make docker-deps-up

# command to install dependencies
install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install -e ."

after_success:
  - /bin/bash deploy
  - make docker-deps-down

# command to run tests
script: pytest
notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
